config/routes.rb
Rails.application.routes.draw do
  get 'stimulus/imdb'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/imdb", to: "lists#index"
  post "/imdb/import", to: "lists#import_and_create"
  get "imdb/:id", to: "lists#show"
  post "/imdb/filter", to: "lists#filter", as: :imdb_filter
  get "/fluxfm", to: "fluxfm#index"
  get "/nasa", to: "nasa#index"
  get "/freeadvise", to: "freeadvise#index"
  resources :tasks

  scope "/imdb" do
    resources :lists, only: [:edit, :update, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
require "csv"
require "nokogiri"
require "open-uri"

class List < ApplicationRecord
  belongs_to :user
  has_many :movies, dependent: :destroy

  before_destroy :prevent_default_list_deletion


  def self.import(file, list_id)
    CSV.foreach(file.path, headers: true) do |row|
      Movie.create!(
        title: row["Title"],
        title_type: row["Title Type"],
        imdb_rating: row["IMDb Rating"],
        genre: row["Genres"],
        year: row["Year"],
        imdb_id: row["Const"],
        list_id: list_id
      )
    end
  end

  private

    def prevent_default_list_deletion
      if name == "Default List"
        errors.add(:base, "Cannot delete the default list.")
        throw(:abort)
      end
    end

end

app/models/movie.rb
require "csv"
class Movie < ApplicationRecord
  belongs_to :list
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
require "csv"

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_many :lists, dependent: :destroy
  has_many :tasks, dependent: :destroy

  after_create :create_default_list

  private

  def create_default_list
    default_list = lists.create(name: "Default List", user: self)

    file_path = "db/storage/Default-Watchlist.csv"
    CSV.foreach(file_path, headers: true) do |row|
      Movie.create!(
        title: row["Title"],
        title_type: row["Title Type"],
        imdb_rating: row["IMDb Rating"],
        genre: row["Genres"],
        year: row["Year"],
        imdb_id: row["Const"],
        list_id: default_list.id
      )
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/fluxfm_controller.rb
class FluxfmController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
    date = params[:date].presence || Date.today
    url = "https://archiv.fluxfm.de/fluxfm-playlist/?loc=berlin&date=#{date}&ajax=1&days=30&limit=30"
    puts "Generated URL: #{url}"
    html = URI.open(url)
    doc = Nokogiri::HTML.parse(html)
    @songs = doc.search(".title")


    # @user = RSpotify::User.find("1193316999")
    # playlist = @user.create_playlist!('FluxFm Top 30')
    # songs.each do |song|
    #   # Search for the song on Spotify
    #   tracks = RSpotify::Track.search(song)
    #   playlist.add_tracks!(tracks)
    # end
  end

end

app/controllers/freeadvise_controller.rb
class FreeadviseController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    url = "https://api.adviceslip.com/advice"
    advise_serialized = URI.parse(url).read
    @advise = JSON.parse(advise_serialized)
  end

end

app/controllers/lists_controller.rb
require "nokogiri"
require "open-uri"
require "json"
require 'rspotify'

class ListsController < ApplicationController
  def index
    @lists = current_user.lists
    @movies = Movie.all
    @list = List.find_by(params[:list_id])
  end

  def import_and_create
    @list = List.new(list_params) # Uses list_params to get the list's name
    @list.user = current_user # Assign the current user to the list
    @list.save
    if params[:file].present?
      List.import(params[:file], @list.id) # Pass the file and the list to the import method
      redirect_to imdb_path, notice: "List and movies imported successfully"
    else
      @list.destroy
      redirect_to imdb_path, alert: "No file selected. List creation canceled."
    end
  end

  def filter
    if params[:list_id].present?
      @list = List.find(params[:list_id])
      @filtered_movies = @list.movies.all

      if params[:min_imdb_rating].present? && params[:max_imdb_rating].present?
        min_rating = params[:min_imdb_rating]
        max_rating = params[:max_imdb_rating]
        @filtered_movies = @filtered_movies.where("imdb_rating BETWEEN ? AND ?", min_rating, max_rating)
      end

      if params[:genre].present?
        genre = params[:genre].capitalize
        @filtered_movies = @filtered_movies.where("genre LIKE ?", "%#{genre}%")
      end

      if params[:media].present?
        @filtered_movies = @filtered_movies.where("title_type = ?", params[:media])
      end

      respond_to do |format|
        format.html { render :index }
        format.turbo_stream { render turbo_stream: turbo_stream.replace('movies_list', partial: 'shared/movies_list', locals: { movies: @filtered_movies }) }
      end
    else
      redirect_to imdb_path, alert: "No List selected. Please select a list."
    end
  end

  def destroy
    @list = List.find(params[:id])
    if @list.destroy
      redirect_to imdb_path, alert: "List is deleted."
    else
      redirect_to imdb_path, alert: @list.errors.full_messages.to_sentence
    end
  end

  private

  def list_params
    params.permit(:name)
  end

end

app/controllers/nasa_controller.rb
class NasaController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
    api_key = ENV["NASA_API"]
    date = params[:date].presence || Date.today
    url = "https://api.nasa.gov/planetary/apod?api_key=#{api_key}&start_date=#{date}"
    image_serialized = URI.parse(url).read
    @image = JSON.parse(image_serialized)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = current_user.tasks.order(due_date: :asc)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :due_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fluxfm/index.html.erb
<h2 class="h1-title mb-4">Flux Fm Top 30 Songs of the Month</h2>

<%= form_with url: fluxfm_path, method: :get, local: false, remote: true do |form| %>
  <div class="flux-search">
    <%= form.date_field :date, class: "flux-date", min: "2022-01-01", max: Date.today, value: (params[:date] || Date.today) %>
    <%= form.submit "Search", class: "flux-save btn btn-secondary btn-sm" %>
  </div>
<% end %>

<div class="mt-3 ">
  <%= render "shared/songs" %>
</div>

app/views/freeadvise/index.html.erb
<div class="container mt-4">
  <h2 class="mb-5 h1-title">Free advise: guaranteed to work, or your money back! 🙃 </h2>
  <h3 class="free-advise mt-5"><%= @advise["slip"]["advice"] %></h3>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SreeSpace - Random Stuff</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <link rel="icon" href="favicon.ico" />
    <%= favicon_link_tag ('favicon.ico') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container mt-3">
      <%= yield %>
    </div>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/lists/filter.turbo_stream.erb
<%= turbo_stream.replace "movies_list" do %>
  <%= render partial: "shared/movies_list", locals: { movies: @filtered_movies } %>
<% end %>

app/views/lists/fluxindex.html.erb
<h2 class="h1-title mb-4">Flux Fm Top 30 Songs of the Month</h2>

<%= form_with url: fluxfm_path, method: :get, local: false, remote: true do |form| %>
  <div class="flux-search">
    <%= form.date_field :date, class: "flux-date", min: "2022-01-01", max: Date.today, value: (params[:date] || Date.today) %>
    <%= form.submit "Search", class: "flux-save btn btn-secondary btn-sm" %>
  </div>
<% end %>

<div class="mt-3 ">
  <%= render "shared/songs" %>
</div>

app/views/lists/index.html.erb
<div class="container mt-4">
  <h2 class="mb-4 h1-title">IMDB Watchlist Helper</h2>

  <div class="mb-4 addlist">
    <h5 class="add-watchlist mb-4 green-button">Add IMDb Watchlist</h5>
    <div class="watchlist-form d-none"><%= render "shared/addlist_form" %></div>
  </div>

  <div class="mb-4">
    <h5 class="search-list">Search IMDb Watchlist</h5>
    <%= render "shared/filter_form" %>
  </div>

  <%# filter turbo stream file will execute this list %>
  <div id="movies_list" class="mt-4"></div>

</div>

app/views/lists/nasa.html.erb
<div class="container mt-4">
  <h2 class="mb-4 h1-title">NASA Image Of The Day</h2>
  <%= form_with url: nasa_path, method: :get, local: false, remote: true do |form| %>
    <div class="nasa-search">
      <%= form.date_field :date, class: "nasa-date", min: "2023-01-01", max: Date.today, value: (params[:date] || Date.today) %>
      <%= form.submit "Search", class: "nasa-save btn btn-secondary btn-sm" %>
    </div>
  <% end %>
  <figure class="nasa-image-title">
    <figcaption>
      <h4><%= @image[0]["title"] %></h4>
      <p><%= @image[0]["date"] %></p>
      <p><%= @image[0]["explanation"] %></p>
    </figcaption>
    <img class= "nasa-img" src="<%= @image[0]["url"] %>" alt="NASA image of the day">
  </figure>

  <span class="nasa-img-credit">"Image Credit: NASA, APOD (Astronomy Picture of the Day)"</span>

</div>

app/views/nasa/index.html.erb
<div class="container mt-4">
  <h2 class="mb-4 h1-title">NASA Image Of The Day</h2>
  <%= form_with url: nasa_path, method: :get, local: false, remote: true do |form| %>
    <div class="nasa-search mb-2">
      <%= form.date_field :date, class: "nasa-date", min: "2023-01-01", max: Date.today, value: (params[:date] || Date.today) %>
      <%= form.submit "Search", class: "nasa-save btn btn-secondary btn-sm" %>
    </div>
  <% end %>
  <figure class="nasa-image-title">
    <figcaption>
      <h4><%= @image[0]["title"] %></h4>
      <p><%= @image[0]["date"] %></p>
      <p><%= @image[0]["explanation"] %></p>
    </figcaption>
    <img class= "nasa-img" src="<%= @image[0]["url"] %>" alt="NASA image of the day">
  </figure>

  <span class="nasa-img-credit">"Image Credit: NASA, APOD (Astronomy Picture of the Day)"</span>

</div>

app/views/pages/home.html.erb
<h1>Projects</h1>

<div class="imdb-home">
  <%= link_to "IMDB Helper", imdb_path %>
</div>

<div class="fluxfm-home">
  <%= link_to "FluxFM top 30", fluxfm_path %>
</div>

<div class="nasa-home">
  <%= link_to "NASA Image Of The Day", nasa_path %>
</div>

<div class="freeadvise">
  <%= link_to "Free Advise", freeadvise_path %>
</div>

<div class="todo-tasks">
  <%= link_to "To-Do Tasks", tasks_path %>
</div>

app/views/shared/_addlist_form.html.erb
<div class="dropdown">
  <div class="mt-4 addlist-form">
    <%= form_with url: imdb_import_path, method: :post, local: false, html: { multipart: true }, remote: true, class: 'form' do |form| %>
      <div class="form-group mb-3">
        <%= form.label :name, "List Name", class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group mb-3">
        <%= form.label :file, "Select File", class: 'form-label' %>
        <%= form.file_field :file, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.submit "Save List", class: 'btn green-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_filter_form.html.erb
<%= form_with url: imdb_filter_path, method: :post, remote: true, html: { class: 'form-inline' } do |form| %>
  <div class="form-group mb-2">
    <%= form.collection_select :list_id, @lists, :id, :name, { prompt: "Select list" }, { class: "form-control" } %>
  </div>

  <div class="form-group mb-2 row g-2">
    <div class="col">
      <%= form.select :media, options_for_select(["Movie", "TV Series"], selected: params[:media]), {}, class: 'form-control' %>
    </div>
    <div class="col">
      <%= form.text_field :genre, value: params[:genre], placeholder: 'Genre', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group mb-2 row g-2">
    <div class= "col">
      <%= form.number_field :min_imdb_rating, step: 0.1, min: 0, max: 10, value: params[:min_imdb_rating], placeholder: 'Min Rating', class: 'form-control' %>
    </div>
    <div class= "col">
      <%= form.number_field :max_imdb_rating, step: 0.1, min: 0, max: 10, value: params[:max_imdb_rating], placeholder: 'Max Rating', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group mb-2 d-flex justify-content-between">
    <%= form.submit "Filter", class: 'btn green-button' %>
    <% if @list.present? %>
      <%= link_to "Delete", list_path(@list), method: :delete,  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn red-button" %>
    <% end %>
  </div>

<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_movies_list.html.erb
<div id="movies_list">
  <% if movies.any? %>
    <p><%= movies.count %> Items found</p>
    <ul class="movie-list" data-controller="imdb">
      <% movies.each do |movie| %>
        <%# data-imdb-id - custom data set. Invisible for user %>
        <li class ="mb-2" data-action="click->imdb#imdbinfo" data-imdb-id="<%= movie.imdb_id %>" >
          <b><%= movie.title %></b> (<%= movie.year %>) - <%= movie.imdb_rating %> <br>
          <%= movie.genre %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>No movies found.</p>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid d-flex">
    <div class="navitems">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "iceman.png", class: "iceman-logo" %>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="navbar-right d-flex justify-content-around" >
        <div class= "login-bar">
          <%= link_to "", destroy_user_session_path, data: {turbo_method: :delete}, title: "Log out", class: "mx-2 dropdown-item fa-solid fa-right-from-bracket" %>
        </div>
      </div>
    <% else %>
      <div class="signin">
        <%= link_to "", new_user_session_path, title: "Log in",  class: " mx-2 dropdown-item fa-solid fa-right-to-bracket" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_songs.html.erb
  <ol>
    <% @songs.each do |song| %>
      <li class= "mb-1"> <%= song.text.strip %></li>
    <% end %>
  </ol>

app/views/tasks/edit.html.erb
<h2>Edit Task</h2>
<%= form_with model: @task, class: "form-horizontal" do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", placeholder: "Enter task name" %>
  </div>
  <div class="mb-3">
    <%= form.label :due_date, class: "form-label" %>
    <%= form.date_field :due_date, value: @task.due_date || Date.today, class: "form-control" %>
  </div>
  <div class="d-grid gap-2">
    <%= form.submit "Update Task", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<h2 class="mb-4 h1-title">To-do List</h2>


<div class= "d-flex justify-content-between">
  <%= link_to "New Task", new_task_path, class: "btn green-button mb-3" %>
</div>

<div class="display-tasks">
  <ol class= "list-group">
    <% @tasks.each do |task| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">

        <div class="d-flex">
          <input type="checkbox" class="form-check-input me-2">
          <span class="task-name"><%= task.name %></span>
        </div>

        <div class="dd">
          <span class="task-date"><%= task.due_date.strftime("%d-%b") %></span>
          <%= link_to "Edit", edit_task_path(task), class: "btn green-button task-edit" %>
          <%= link_to "Del", task, data: { turbo_method: 'delete', turbo_confirm: 'Are you sure?' }, class: "btn red-button task-delete" %>
        </div>

      </li>
    <% end %>
  </ol>
</div>

app/views/tasks/new.html.erb
<h2 class="mb-4">Add a New Task</h2>
<%= form_with model: @task, method: :post, url: tasks_path do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, maxlength: 21, class: "form-control", placeholder: "Enter task name" %> 
  </div>
  <div class="mb-3">
    <%= form.label :due_date, class: "form-label" %>
    <%= form.date_field :due_date, value: Date.today, class: "form-control" %>
  </div>
  <%= form.submit "Create Task", class: "btn btn-primary" %>
<% end %>